Update bundle-updater.yml

diff --git a/.github/workflows/bundle-updater.yml b/.github/workflows/bundle-updater.yml
--- a/.github/workflows/bundle-updater.yml
+++ b/.github/workflows/bundle-updater.yml
@@ -124,17 +124,22 @@ jobs:
         working-directory: ${{ github.workspace }}
 
       - name: Download changed files artifact
-        uses: actions/download-artifact@v4.1.7
+        uses: actions/download-artifact@v4
         with:
           name: changed_files
-          path: changed_files.zip
+          path: changed_files
 
       - name: Verify artifact download
-        run: ls -l
+        run: ls -l changed_files
         working-directory: ${{ github.workspace }}
 
       - name: Unzip artifact
-        run: unzip -o changed_files.zip
+        run: |
+          unzip_result=$(unzip -o changed_files/changed_files.zip)
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to unzip the artifact: $unzip_result"
+            exit 1
+          fi
         working-directory: ${{ github.workspace }}
 
       - name: List contents of directory after unzip
@@ -145,5 +150,5 @@ jobs:
         run: |
           while IFS= read -r file; do
             git checkout HEAD -- "$file"
-          done < changed_files.txt
+          done < changed_files/changed_files.txt
         working-directory: ${{ github.workspace }}
