Fix

diff --git a/.github/workflows/manager-update-checker.yml b/.github/workflows/manager-update-checker.yml
--- a/.github/workflows/manager-update-checker.yml
+++ b/.github/workflows/manager-update-checker.yml
@@ -19,21 +19,26 @@ jobs:
 
       - name: Get artifact URL and run Python script
         run: |
-            ARTIFACT_URL=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].artifacts_url')
-            if [ -z "$ARTIFACT_URL" ]; then
-              echo "Failed to fetch artifact URL."
-              exit 1
-            fi
-            ARTIFACT_ID=$(curl -sS "$ARTIFACT_URL" | jq -r '.artifacts[] | select(.name == "revanced-manager") | .id')
-            if [ -z "$ARTIFACT_ID" ]; then
-              echo "Failed to fetch artifact ID."
-              exit 1
-            fi
-            ARTIFACT_DOWNLOAD_URL=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/artifacts/$ARTIFACT_ID/zip" | jq -r '.archive_download_url')
-            echo "ARTIFACT_URL=$ARTIFACT_DOWNLOAD_URL" >> $GITHUB_ENV
-            curl -sSL -o artifact.zip "${ARTIFACT_DOWNLOAD_URL}"
-            unzip -q artifact.zip -d artifact
-            python get_compose_artifact.py
+         ARTIFACT_URL=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].artifacts_url')
+         if [ -z "$ARTIFACT_URL" ]; then
+          echo "Failed to fetch artifact URL."
+          exit 1
+         fi
+         ARTIFACT_ID=$(curl -sS "$ARTIFACT_URL" | jq -r '.artifacts[] | select(.name == "revanced-manager") | .id')
+         echo "ARTIFACT_ID: $ARTIFACT_ID"
+         if [ -z "$ARTIFACT_ID" ]; then
+          echo "Failed to fetch artifact ID."
+          exit 1
+         fi
+         ARTIFACT_DOWNLOAD_URL=$(curl -sS "https://api.github.com/repos/ReVanced/revanced-manager/actions/artifacts/$ARTIFACT_ID/zip" | jq -r '.archive_download_url')
+         echo "ARTIFACT_URL: $ARTIFACT_DOWNLOAD_URL"
+         echo "ARTIFACT_ID: $ARTIFACT_ID"
+         echo "Downloading artifact from: $ARTIFACT_DOWNLOAD_URL"
+         echo "ARTIFACT_URL=$ARTIFACT_DOWNLOAD_URL" >> $GITHUB_ENV
+         curl -sSL -o artifact.zip "${ARTIFACT_DOWNLOAD_URL}"
+         unzip -q artifact.zip -d artifact
+         python get_compose_artifact.py
+    
         
         
         
