Fix

diff --git a/.github/workflows/manager-update-checker.yml b/.github/workflows/manager-update-checker.yml
--- a/.github/workflows/manager-update-checker.yml
+++ b/.github/workflows/manager-update-checker.yml
@@ -6,7 +6,7 @@ on:
     - cron: "0 0 * * *"
 
 jobs:
-  get-artifact-url-and-run:
+  update-readme:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -17,24 +17,20 @@ jobs:
           sudo apt-get install jq -y
           python -m pip install requests
 
-      - name: Get artifact URL and run Python script
+      - name: Get artifact URL and update README
         run: |
-            ARTIFACT_URL=$(curl -sS -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].artifacts_url')
-            if [ -z "$ARTIFACT_URL" ]; then
-              echo "Failed to fetch artifact URL."
-              exit 1
-            fi
-            ARTIFACT_ID=$(curl -sS "$ARTIFACT_URL" | jq -r '.artifacts[] | select(.name == "revanced-manager") | .id')
-            if [ -z "$ARTIFACT_ID" ]; then
-              echo "Failed to fetch artifact ID."
-              exit 1
-            fi
-            ARTIFACT_DOWNLOAD_URL="https://github.com/ReVanced/revanced-manager/actions/runs/${GITHUB_RUN_ID}/artifacts/${ARTIFACT_ID}"
-            echo "ARTIFACT_URL: $ARTIFACT_DOWNLOAD_URL"
-            python get_compose_artifact.py $ARTIFACT_DOWNLOAD_URL
-        
-        
-    
-        
-        
-        
+          ARTIFACT_URL=$(curl -sS -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/ReVanced/revanced-manager/actions/workflows/pr-build.yml/runs?event=pull_request&status=success" | jq -r '.workflow_runs[0].artifacts_url')
+          if [ -z "$ARTIFACT_URL" ]; then
+            echo "Failed to fetch artifact URL."
+            exit 1
+          fi
+          ARTIFACT_ID=$(curl -sS "$ARTIFACT_URL" | jq -r '.artifacts[] | select(.name == "revanced-manager") | .id')
+          if [ -z "$ARTIFACT_ID" ]; then
+            echo "Failed to fetch artifact ID."
+            exit 1
+          fi
+          ARTIFACT_DOWNLOAD_URL="https://github.com/ReVanced/revanced-manager/actions/runs/${GITHUB_RUN_ID}/artifacts/${ARTIFACT_ID}"
+          python update_readme.py $ARTIFACT_DOWNLOAD_URL
+        env:
+          GITHUB_RUN_ID: ${{ github.run_id }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
